### ISSUE TITLE
Visited List Functionality

### ISSUE THREAD

**Issue by kaohman** [kaohman/national-parks#17]
- [x] View visited list button can be clicked, checks local storage and updates the map via App's state, current parks and re-render of map.
- [x] Icon in pop-up can be clicked.
- [x] When icon is clicked, add to local storage
- [x] When icon is clicked, also updates number in button below map.

**Comment by trbachmann** [comment]
Add icon and functionality when clicked, to add to localStorage. Still need to create functionality that updates numbers in button below map

**Comment by kaohman** [comment]
Do we still need to add functionality to toggle/remove from visited or bucket lists when clicked?
