### ISSUE TITLE
Style Pages

### ISSUE THREAD

**Issue by kaohman** [kaohman/national-parks#21]
- [x] Landing Page
- [x] Homepage
- [x] Parks pop-up - also need icons for visited/bucket list
- [x] State display
- [x] Style buttons in park pop-up to be centered, colors matching marker icons etc. - Tiffany
- [x] Add hover text pop-up on visited/bucket list icons. - Tiffany
- [x] Add hover state to delete icon on park pop-up, color red and increase size slightly - Tiffany
- [x] Set description height and include overflow scrollbar. - Tiffany
- [x] Remove button styling on icons - Tiffany
- [x] Increase icon size on hover - Tiffany
- [x] Figure out overlay issue - Karin
- [x] Look into changing map icons to green -Karin
- [x] Style state card, add chart. - Adam

**Comment by kaohman** [comment]
Started working on pop-up for parks, still need icons and full card display functionality.

**Comment by kaohman** [comment]
Initial styling done - need to work on responsive layout and state cards.

**Comment by trbachmann** [comment]
Added font awesome links and icons for visited parks, bucket list and delete on the park popup

**Comment by kaohman** [comment]
-[ ] Style buttons in park pop-up to be centered, etc.
-[ ] Set description height and include overflow scrollbar.
-[ ] Figure out overlay issue
